apiVersion: apps/v1
kind: Deployment
metadata:
  name: samstore-deploy
  labels:
    app: samstore-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samstore-pod
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: samstore-pod
    spec:
      containers:
      - name: samstore
        image: nogada/sam-icp4a:v6
        ports:
        - containerPort: 8080
          name: tomcat
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /liveness
            port: tomcat
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /ready
            port: tomcat
          initialDelaySeconds: 30
          periodSeconds: 5
      #   volumeMounts:
      #   - name: application-property
      #     mountPath: /config
      # volumes:
      # - name: application-property
      #   configMap:
      #   # Provide the name of the ConfigMap containing the files you want
      #   # to add to the container
      #     name: datasource
